### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '/data'

### ISSUE THREAD

**Issue by Wang-Qinyu** [FateScript/CenterNet-better#45]
I meet **PermissionError: [Errno 13] Permission denied: '/data'** when I train my model. And I get the path which cause this error: 
`/data/Outputs/model_logs/playground/centernet.res18.coco.512size`

Then I run `chmod 777 /data`,it also throw that error.

The detail error is below:

soft link to /data/Outputs/model_logs/playground/centernet.res18.coco.512size
Command Line Args: Namespace(dist_url='tcp://127.0.0.1:50163', eval_only=False, machine_rank=0, num_gpus=2, num_machines=1, opts=[], resume=False)
Traceback (most recent call last):
  File "/home/wangqinyu/STR/CenterNet-better/tools/train_net.py", line 125, in <module>
    args=(args,),
  File "/home/wangqinyu/STR/CenterNet-better/dl_lib/engine/launch.py", line 50, in launch
    daemon=False,
  File "/home/wangqinyu/anaconda3/envs/STR/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/wangqinyu/anaconda3/envs/STR/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/home/wangqinyu/anaconda3/envs/STR/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/wangqinyu/anaconda3/envs/STR/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/home/wangqinyu/STR/CenterNet-better/dl_lib/engine/launch.py", line 85, in _distributed_worker
    main_func(*args)
  File "/home/wangqinyu/STR/CenterNet-better/tools/train_net.py", line 79, in main
    cfg, logger = default_setup(config, args)
  File "/home/wangqinyu/STR/CenterNet-better/dl_lib/engine/defaults.py", line 95, in default_setup
    PathManager.mkdirs(output_dir)
  File "/home/wangqinyu/STR/CenterNet-better/dl_lib/utils/file_io.py", line 447, in mkdirs
    return PathManager.__get_path_handler(path)._mkdirs(path)
  File "/home/wangqinyu/STR/CenterNet-better/dl_lib/utils/file_io.py", line 253, in _mkdirs
    os.makedirs(path, exist_ok=True)
  File "/home/wangqinyu/anaconda3/envs/STR/lib/python3.7/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/wangqinyu/anaconda3/envs/STR/lib/python3.7/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/wangqinyu/anaconda3/envs/STR/lib/python3.7/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  [Previous line repeated 1 more time]
  File "/home/wangqinyu/anaconda3/envs/STR/lib/python3.7/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/data'

**Comment by FateScript** [comment]
Please check if your dir exist or change your [OUTPUT_DIR](https://github.com/FateScript/CenterNet-better/blob/master/playground/centernet.res18.coco.512size/config.py#L66) to another value

**Comment by ccfarah** [comment]
Same issue as above. Is this tied to the set-up of the datasets folder? I see the expected COCO structure but following README did not populate the datasets folder. Could you provide a little more detail around that? Thanks!

**Comment by FateScript** [comment]
For coco dataset, please fellow [this README](https://github.com/FateScript/CenterNet-better/tree/master/datasets) to create softlink. OUTPUT_DIR is used to save dumped models and logs, if you setup this repo correctly(no error logging), there are no need to build it twice.

**Comment by ccfarah** [comment]
Thanks FateScript! Setting it up now.
